### ISSUE TITLE
rake spec test failures

### ISSUE THREAD

**Issue by dbut023** [kputnam/piggly#25]
Ubuntu 12.04.5 (x86_64)
Ruby 2.2.4p230 (x86_64)

Fresh git checkout, `bundle install` ran OK,
`bundle exec rake spec` fails with 3 test failures:

```
Failures:

  1) Piggly::Dumper::Index when cache file exists when the cache index file has two entries has two procedures
     Failure/Error: @first  = Dumper::ReifiedProcedure.from_hash \
     NoMethodError:
       undefined method `split' for nil:NilClass
     # ./lib/piggly/dumper/reified_procedure.rb:66:in `defaults'
     # ./lib/piggly/dumper/reified_procedure.rb:137:in `from_hash'
     # ./spec/examples/dumper/index_spec.rb:35:in `block (4 levels) in <module:Piggly>'

  2) Piggly::Dumper::Index when cache file exists when the cache index file has two entries is indexed by identifier
     Failure/Error: @first  = Dumper::ReifiedProcedure.from_hash \
     NoMethodError:
       undefined method `split' for nil:NilClass
     # ./lib/piggly/dumper/reified_procedure.rb:66:in `defaults'
     # ./lib/piggly/dumper/reified_procedure.rb:137:in `from_hash'
     # ./spec/examples/dumper/index_spec.rb:35:in `block (4 levels) in <module:Piggly>'

  3) Piggly::Dumper::Index when cache file exists when the cache index file has two entries reads each procedure's source_path
     Failure/Error: @first  = Dumper::ReifiedProcedure.from_hash \
     NoMethodError:
       undefined method `split' for nil:NilClass
     # ./lib/piggly/dumper/reified_procedure.rb:66:in `defaults'
     # ./lib/piggly/dumper/reified_procedure.rb:137:in `from_hash'
     # ./spec/examples/dumper/index_spec.rb:35:in `block (4 levels) in <module:Piggly>'

Finished in 1.21 seconds
291 examples, 3 failures, 60 pending

Failed examples:

rspec ./spec/examples/dumper/index_spec.rb:55 # Piggly::Dumper::Index when cache file exists when the cache index file has two entries has two procedures
rspec ./spec/examples/dumper/index_spec.rb:59 # Piggly::Dumper::Index when cache file exists when the cache index file has two entries is indexed by identifier
rspec ./spec/examples/dumper/index_spec.rb:64 # Piggly::Dumper::Index when cache file exists when the cache index file has two entries reads each procedure's source_path
```

**Comment by kputnam** [comment]
I think this was fixed in #26. Please reopen if that's not the case.
